# Generated by Django 3.2.23 on 2024-03-17 07:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='avatars/no-image.jpeg', upload_to='avatars', verbose_name='Аватар')),
                ('bio', models.CharField(max_length=150, null=True, verbose_name='Информация о пользователе')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='Номер телефона')),
                ('gender', models.CharField(choices=[('мужской', 'Мужской'), ('женский', 'Женский'), ('не указано', 'Предпочитаю не указывать'), ('свой вариант', 'Свой вариант')], default='не указано', max_length=50, verbose_name='Пол')),
                ('custom_gender', models.CharField(blank=True, max_length=50, null=True, verbose_name='Свой вариант пола')),
                ('publication_count', models.PositiveIntegerField(default=0, verbose_name='Количество публикаций')),
                ('following_count', models.PositiveIntegerField(default=0, verbose_name='Количество подписок')),
                ('followers_count', models.PositiveIntegerField(default=0, verbose_name='Количество подписчиков')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
