# Generated by Django 3.2.23 on 2024-03-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inst_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='comment',
            field=models.IntegerField(default=0, verbose_name='комментарий'),
        ),
        migrations.AddField(
            model_name='publication',
            name='like',
            field=models.IntegerField(default=0, verbose_name='лайк'),
        ),
    ]
