# Generated by Django 3.2.23 on 2024-03-19 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inst_app', '0004_follower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='liked',
        ),
    ]
