# Generated by Django 3.2.23 on 2024-03-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inst_app', '0005_remove_like_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='image',
            field=models.ImageField(upload_to='posts', verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='text',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
